# Generated by Django 5.0.7 on 2024-07-18 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("brand", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=30)),
                ("size", models.CharField(blank=True, max_length=30)),
                ("unique_features", models.TextField(blank=True)),
                ("date_found", models.DateField()),
                ("location_found", models.CharField(max_length=100)),
                ("photo", models.ImageField(blank=True, upload_to="found_items/")),
                ("is_notified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("brand", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=30)),
                ("size", models.CharField(blank=True, max_length=30)),
                ("unique_features", models.TextField(blank=True)),
                ("date_lost", models.DateField()),
                ("location_lost", models.CharField(max_length=100)),
                ("photo", models.ImageField(blank=True, upload_to="lost_items/")),
                ("is_matched", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
