# Generated by Django 5.0.7 on 2024-07-18 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lostandfound", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="founditem",
            options={"ordering": ["-date_found"]},
        ),
        migrations.AlterModelOptions(
            name="lostitem",
            options={"ordering": ["-date_lost"]},
        ),
        migrations.AddField(
            model_name="founditem",
            name="lost_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="found_items",
                to="lostandfound.lostitem",
            ),
        ),
    ]
