# Generated by Django 5.0.7 on 2024-07-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lostandfound", "0004_alter_lostitem_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="founditem",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="lostitem",
            name="photo",
        ),
        migrations.AddField(
            model_name="founditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="found_items/"),
        ),
        migrations.AddField(
            model_name="lostitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lost_items/"),
        ),
    ]
