# Generated by Django 5.0.7 on 2024-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lostandfound", "0005_remove_founditem_photo_remove_lostitem_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founditem",
            name="brand",
            field=models.CharField(max_length=50),
        ),
    ]
